[project]
name = "fastapi-user-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aioredis>=2.0.1",
    "alembic>=1.14.1",
    "asyncpg>=0.30.0",
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
]
